FROM ubuntu:bionic

# VSCode extensions
RUN apt-get update && apt-get install -y bsdtar curl zip
RUN mkdir -p /plugins

RUN curl -JL https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/configuration-editing-1.39.1-prel.vsix | bsdtar -xvf - extension && \
    mv extension /plugins/vscode-builtin-configuration-editing/ && \
    curl -JL https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/css-1.39.1-prel.vsix | bsdtar -xvf - extension && \
    mv extension /plugins/vscode-builtin-css/ && \
    curl -JL https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/docker-1.39.1-prel.vsix | bsdtar -xvf - extension && \
    mv extension /plugins/vscode-builtin-docker/ && \
    curl -JL https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/html-1.39.1-prel.vsix | bsdtar -xvf - extension && \
    mv extension /plugins/vscode-builtin-html/ && \
    curl -JL https://open-vsx.org/api/vscode/html-language-features/1.49.0/file/vscode.html-language-features-1.49.0.vsix | bsdtar -xvf - extension && \
    mv extension /plugins/vscode-builtin-html-language-features/ && \
    curl -JL https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/javascript-1.39.1-prel.vsix | bsdtar -xvf - extension && \
    mv extension /plugins/vscode-builtin-javascript/ && \
    curl -JL https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/json-1.39.1-prel.vsix | bsdtar -xvf - extension && \
    mv extension /plugins/vscode-builtin-json/ && \
    curl -JL https://open-vsx.org/api/vscode/json-language-features/1.46.1/file/vscode.json-language-features-1.46.1.vsix | bsdtar -xvf - extension && \
    mv extension /plugins/vscode-builtin-json-language-features/ && \
    curl -JL https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/markdown-1.39.1-prel.vsix | bsdtar -xvf - extension && \
    mv extension /plugins/vscode-builtin-markdown/ && \
    curl -JL https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/merge-conflict-1.39.1-prel.vsix | bsdtar -xvf - extension && \
    mv extension /plugins/vscode-builtin-merge-conflicts/ && \
    curl -JL https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/npm-1.39.1-prel.vsix | bsdtar -xvf - extension && \
    mv extension /plugins/vscode-builtin-npm/ && \
    curl -JL https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/python-1.39.1-prel.vsix | bsdtar -xvf - extension && \
    mv extension /plugins/vscode-builtin-python/ && \
    curl -JL https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/r-1.39.1-prel.vsix | bsdtar -xvf - extension && \
    mv extension /plugins/vscode-builtin-r/ && \
    curl -JL https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/shellscript-1.39.1-prel.vsix | bsdtar -xvf - extension && \
    mv extension /plugins/vscode-builtin-shellscript/ && \
    curl -JL https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/sql-1.39.1-prel.vsix | bsdtar -xvf - extension && \
    mv extension /plugins/vscode-builtin-sql/ && \
    curl -JL https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/typescript-1.39.1-prel.vsix | bsdtar -xvf - extension && \
    mv extension /plugins/vscode-builtin-typescript/ && \
    curl -JL https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/typescript-language-features-1.39.1-prel.vsix | bsdtar -xvf - extension && \
    mv extension /plugins/vscode-builtin-typescript-language-features/ && \
    curl -JL https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/xml-1.39.1-prel.vsix | bsdtar -xvf - extension && \
    mv extension /plugins/vscode-builtin-xml/ && \
    curl -JL https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/yaml-1.39.1-prel.vsix | bsdtar -xvf - extension && \
    mv extension /plugins/vscode-builtin-yaml/ && \
    curl -JL https://github.com/theia-ide/editorconfig-vscode/releases/download/v0.14.4/EditorConfig-0.14.4.vsix | bsdtar -xvf - extension && \
    mv extension /plugins/vscode-editorconfig/ && \
    curl -JL https://open-vsx.org/api/ms-python/python/2020.8.105369/file/ms-python.python-2020.8.105369.vsix | bsdtar -xvf - extension && \
    mv extension /plugins/vscode-python/


# zip and copy to host
RUN zip -r plugins.zip /plugins
FROM scratch AS export-stage
COPY --from=0 /plugins.zip .