FROM ubuntu:bionic

# add theia deb and plugins
COPY ./out/plugins.zip ./out/edsp-theia_0.0.1_all.deb /edsp-theia/

RUN mkdir -p /home/project

# Install Python 3 from source
ARG VERSION=3.8.3
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y make build-essential libssl-dev \
    && apt-get install -y libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
    && apt-get install -y libncurses5-dev  libncursesw5-dev xz-utils tk-dev \
    && wget https://www.python.org/ftp/python/$VERSION/Python-$VERSION.tgz \
    && tar xvf Python-$VERSION.tgz \
    && cd Python-$VERSION \
    && ./configure \
    && make -j8 \
    && make install \
    && cd .. \
    && rm -rf Python-$VERSION \
    && rm Python-$VERSION.tgz

RUN apt-get install -y libsecret-1-0 \
    && apt-get install -y python-dev python-pip \
    && pip install --upgrade pip --user \
    && apt-get install -y python3-dev python3-pip \
    && pip3 install --upgrade pip --user \
    && pip3 install python-language-server flake8 autopep8 \
    && apt-get clean \
    && apt-get auto-remove -y \
    && rm -rf /var/cache/apt/* \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/*

RUN apt-get update && \
    apt-get install -y sudo zip unzip rsync && \
    curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash - && \
    apt-get install -y nodejs
	
RUN dpkg -x /edsp-theia/edsp-theia_0.0.1_all.deb /edsp-theia/ && \
    rsync -a --no-perms /edsp-theia/etc/ /etc/ && \
	rsync -a --no-perms /edsp-theia/usr/ /usr/ && \
	unzip /edsp-theia/plugins.zip

ENV SHELL /bin/bash 
ENV THEIA_DEFAULT_PLUGINS=local-dir:/plugins
ENV USE_LOCAL_GIT true
EXPOSE 3000
CMD ["theia", "start", "--hostname 0.0.0.0"]
